# Generated by Django 5.0.1 on 2024-02-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('aadhar_number', models.CharField(max_length=12)),
                ('memo', models.FileField(upload_to='memos/')),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
